## -- fixtax portugal macrophytes 

taxontable <- update_taxonomy_macrophytes(TU, taxontable_arg = taxontable)
complete_entry <- function(x, s, g, f, o,  c, p, k){
        
        taxontable[original_name == x, c("species", "genus", "family", "order", "class", "phylum", "kingdom") := .(s, g, f, o, c, p, k) ]
        
}
taxontable[stringr::str_detect(original_name, "Mentha pulegium"), 
           c("species", "genus", "family", "order", "class", "phylum", "kingdom", "taxon_state") := 
                   .("Mentha pulegium", "Mentha", "Lamiaceae", "Lamiales", "Magnoliopsida", "Tracheophyta", "Plantae", "drop")]

taxontable[taxon_state == "", original_name]


taxontable[genus=="Thrincia"]
taxontable[original_name == "Leontondon taraxacoides subsp. longirostris"]

taxontable[original_name == "Alnus sp."                         , taxon_state := "drop"]
taxontable[original_name == "Callitriche Cophocarpa"            , taxon_state := "hydrophytes"]
taxontable[original_name == "Nuphar luthea"                     , taxon_state := "hydrophytes"]
taxontable[original_name == "Nymphaea alba ssp. alba"           , taxon_state := "hydrophytes"]
taxontable[original_name == "Rumex hydrolaphatum"               , taxon_state := "drop"]
taxontable[original_name == "Acacia dealbata"                   , taxon_state := "drop"]
taxontable[original_name == "Agrostis castellana"               , taxon_state := "drop"]
taxontable[original_name == "Agrostis pourretii"                , taxon_state := "drop"]
taxontable[original_name == "Allium schmitzii"                  , taxon_state := "drop"]
taxontable[original_name == "Allium sp."                        , taxon_state := "drop" ]
taxontable[original_name == "Amaranthus blitoides"              , taxon_state := "drop" ]
taxontable[original_name == "Amaranthus retroflexus"            , taxon_state := "drop" ]
taxontable[original_name == "Anacyclus radiatus"                              , taxon_state := "drop"]
taxontable[original_name == "Anagallis arvensis"                              , taxon_state := "drop"]
taxontable[original_name == "Andryala integrifolia"                           , taxon_state := "drop"]
taxontable[original_name == "Anthemis arvensis"                               , taxon_state := "drop"]
taxontable[original_name == "Avena barbata"                                   , taxon_state := "drop"]
taxontable[original_name == "Avenula sp."                                     , taxon_state := "drop"]
taxontable[original_name == "Brachypodium phoenicoides"                       , taxon_state := "drop"]
taxontable[original_name == "Briza maxima"                                    , taxon_state := "drop"]
taxontable[original_name == "Bromus diandrus"                                 , taxon_state := "drop"]
taxontable[original_name == "Campanula transtagana"                           , taxon_state := "drop"]
taxontable[original_name == "Carex elata subsp. reuterana"                    , taxon_state := "helophytes"]
taxontable[original_name == "Centaurea nigra ssp. Rivularis"                  , taxon_state := "drop"]
taxontable[original_name == "Cerastium glomeratum"                            , taxon_state := "drop"]
taxontable[original_name == "Chamaemelum mixtum"                              , taxon_state := "drop"]
taxontable[original_name == "Chondrilla juncea"                               , taxon_state := "drop"]
taxontable[original_name == "Clematis campaniflora"                           , taxon_state := "drop"]
taxontable[original_name == "Coleostephus myconis"                            , taxon_state := "drop"]
taxontable[original_name == "Coronilla sp."                                   , taxon_state := "drop"]
taxontable[original_name == "Corrigiola telephiifolia"                        , taxon_state := "drop"]
taxontable[original_name == "Crepis cappilaris"                               , taxon_state := "drop"]
taxontable[original_name == "Crepis lampsanoides"                             , taxon_state := "drop"]
taxontable[original_name == "Cynosurus echinatus"                             , taxon_state := "drop"]
taxontable[original_name == "Datura stramonium"                               , taxon_state := "drop"]
taxontable[original_name == "Daucus carota subsp. maritimus"                  , taxon_state := "drop"]
taxontable[original_name == "Ditrichia viscosa"                               , taxon_state := "drop"]
taxontable[original_name == "Erica arborea"                                   , taxon_state := "drop"]
taxontable[original_name == "Eucalyptus camaldulensis"                        , taxon_state := "drop"]
taxontable[original_name == "Eucalyptus globulus"                             , taxon_state := "drop"]
taxontable[original_name == "Festuca ampla"                                   , taxon_state := "drop"]
taxontable[original_name == "Festuca duriotagana"                             , taxon_state := "drop"]
taxontable[original_name == "Ficus carica"                                    , taxon_state := "drop"]
taxontable[original_name == "Flueggea tinctoria"                              , taxon_state := "drop"]
taxontable[original_name == "Foeniculum vulgare"                              , taxon_state := "drop"]

taxontable[original_name == "Galium broteroanum"                              , taxon_state := "drop"]
taxontable[original_name == "Gastridium ventricosum"                          , taxon_state := "drop"]
taxontable[original_name == "Geranium purpureum"                              , taxon_state := "drop"]
taxontable[original_name == "Geranium sp."                                    , taxon_state := "drop"]
taxontable[original_name == "Glinus lotoides"                                 , taxon_state := "drop"]
taxontable[original_name == "Hedera hibernica"                                , taxon_state := "drop"]
taxontable[original_name == "Heliotropium europaeum"                          , taxon_state := "drop"]
taxontable[original_name == "Holcus annuus"                                   , taxon_state := "drop"]
taxontable[original_name == "Hypericum humifussum"                            , taxon_state := "drop"]
taxontable[original_name == "Hypericum perfoliatum"                           , taxon_state := "drop"]
taxontable[original_name == "Hypericum undulatum"                             , taxon_state := "drop"]
taxontable[original_name == "Lactuca sp."                                     , taxon_state := "drop"]
taxontable[original_name == "Leontondon taraxacoides subsp. longirostris"     , taxon_state := "drop"]
taxontable[original_name == "Linaria triornithophora"                         , taxon_state := "drop"]
taxontable[original_name == "Lolium rigidum"                                  , taxon_state := "drop"]
taxontable[original_name == "Lonicera peryclimenum subsp. peryclimenum"       , taxon_state := "drop"]
taxontable[original_name == "Luzula foresteri"                                , taxon_state := "drop"]
taxontable[original_name == "Luzula sylvatica subsp. henriquesii"             , taxon_state := "drop"]
taxontable[original_name == "Lythrum junceum"                                 , taxon_state := "drop"]
taxontable[original_name == "Medicago polymorpha"                             , taxon_state := "drop"]
taxontable[original_name == "Melica ciliata subsp. magnolii"                  , taxon_state := "drop"]
taxontable[original_name == "Moenchia erecta"                                 , taxon_state := "drop"]
taxontable[original_name == "Myosotis discolor"                               , taxon_state := "drop"]
taxontable[original_name == "Myrtus communis"                                 , taxon_state := "drop"]
taxontable[original_name == "Nerium oleander"                                 , taxon_state := "drop"]
taxontable[original_name == "Paronichia argentea"                             , taxon_state := "drop"]
taxontable[original_name == "Piptatherum miliaceum"                           , taxon_state := "drop"]
taxontable[original_name == "Plantago coronopus ssp. coronopus"               , taxon_state := "drop"]
taxontable[original_name == "Plantago lagopus"                                , taxon_state := "drop"]
taxontable[original_name == "Polycarpon tetraphyllum"                         , taxon_state := "drop"]
taxontable[original_name == "Polypogon monspeliensis"                         , taxon_state := "drop"]
taxontable[original_name == "Portulaca oleracea ssp. Oleracea"                , taxon_state := "drop"]
taxontable[original_name == "Pulicaria paludosa"                              , taxon_state := "drop"]
taxontable[original_name == "Ranunculus bulbosus ssp. aleae var. adscendens"  , taxon_state := "drop"]
taxontable[original_name == "Ranunculus trilobus"                             , taxon_state := "drop"]
taxontable[original_name == "Rosa sp."                                        , taxon_state := "drop"]
taxontable[original_name == "Rubus sp."                                       , taxon_state := "drop"]
taxontable[original_name == "Rubus ulmifolius"                                , taxon_state := "drop"]
taxontable[original_name == "Rumex obtusiflolius"                             , taxon_state := "drop"]
taxontable[original_name == "Rumex pulcher ssp. woodsi"                       , taxon_state := "drop"]
taxontable[original_name == "Ruscus aculeatus"                                , taxon_state := "drop"]
taxontable[original_name == "Salix alba subsp. alba"                          , taxon_state := "drop"]
taxontable[original_name == "Salix atrocinerea"                               , taxon_state := "drop"]
taxontable[original_name == "Salix salviifolia subsp. salviifolia"            , taxon_state := "drop"]
taxontable[original_name == "Sanguisorba verrucosa"                           , taxon_state := "drop"]
taxontable[original_name == "Saponaria officinalis"                           , taxon_state := "drop"]
taxontable[original_name == "Scolymus hispanicus"                             , taxon_state := "drop"]
taxontable[original_name == "Scrophularia canina"                             , taxon_state := "drop"]
taxontable[original_name == "Scrophularia scorodonia"                         , taxon_state := "drop"]
taxontable[original_name == "Sedum sp."                                       , taxon_state := "drop"]
taxontable[original_name == "Selaginella denticulata"                         , taxon_state := "drop"]
taxontable[original_name == "Sherardia arvensis"                              , taxon_state := "drop"]
taxontable[original_name == "Silene gallica"                                  , taxon_state := "drop"]
taxontable[original_name == "Spergularia purpurea"                            , taxon_state := "drop"]
taxontable[original_name == "Tamarix africana"                                , taxon_state := "drop"]
taxontable[original_name == "Teucrium scorodonia"                             , taxon_state := "drop"]
taxontable[original_name == "Trifolium angustifolium"                         , taxon_state := "drop"]
taxontable[original_name == "Trifolium resupinatum"                           , taxon_state := "drop"]
taxontable[original_name == "Ulmus minor"                                     , taxon_state := "drop"]
taxontable[original_name == "Umbilicus rupestris"                             , taxon_state := "drop"]
taxontable[original_name == "Urtica sp."                                      , taxon_state := "drop"]
taxontable[original_name == "Verbena supina"                                  , taxon_state := "drop"]
taxontable[original_name == "Vinca difformis"                                 , taxon_state := "drop"]
taxontable[original_name == "Vincetoxicum nigrum"                             , taxon_state := "drop"]
taxontable[original_name == "Viola riviniana"                                 , taxon_state := "drop"]
taxontable[original_name == "Vitis  vinifera subsp. slyvestris"               , taxon_state := "drop"]
taxontable[original_name == "Vulpia geniculata"                               , taxon_state := "drop"]


taxontable[stringr::str_detect(original_name, "Lycopus europaeus"                             ), taxon_state := "drop"]
taxontable[stringr::str_detect(original_name, "Fraxinus angustifolia subsp. angustifolia"     ), taxon_state := "drop"]
taxontable[stringr::str_detect(original_name, "Lythrum salicaria"                             ), taxon_state := "drop"]
taxontable[stringr::str_detect(original_name, "Prunella vulgaris"                             ), taxon_state := "drop"]


taxontable[original_name == "Urtica sp."]
complete_entry("Urtica sp.", NA, "Urtica", "Urticaceae", "Rosales", "Magnoliopsida", "Tracheophyta", "Plantae")
taxontable[genus == "Urtica"]

saveRDS(taxontable, "data/macrophytes/2022-06-14_taxontable_macrophytes.rds")
