taxontable <- dfm$append_to_tt(original_name = "BRACHYSIRA  F.T. Kützing"                                     , fixed_name = "Brachysira", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "FRUSTULIA  L. Rabenhorst"                                     , fixed_name = "Frustulia", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "CRATICULA  A. Grunow"                                         , fixed_name = "Craticula", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "PLEUROSIGMA  W.Smith"                                         , fixed_name = "Gyrosigma", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "MAYAMAEA Lange-Bertalot"                                      , fixed_name = "Mayamaea", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "ENCYONOPSIS Krammer"                                          , fixed_name = "Encyonopsis", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "CYMATOPLEURA  W. Smith"                                       , fixed_name = "Cymatopleura", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "Pinnularia divergens W.M.Sm.var. sublinearis Cleve"           , fixed_name = "Pinnularia divergens", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "MELOSIRA  C.A. Agardh"                                        , fixed_name = "Melosira"     , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "SEMIORBIS  R. Patrick"                                        , fixed_name = "Semiorbis"    , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "CAVINULA  D.G. Mann & A.J. Stickle"                           , fixed_name = "Cavinula"     , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "HIPPODONTA Lange-Bertalot. Metzeltin & Witkowski"             , fixed_name = "Hippodonta"   , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "THALASSIOSIRA  P.T. Cleve"                                    , fixed_name = "Thalassiosira", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "DENTICULA  F.T. Kützing"                                      , fixed_name = "Denticula"   , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "LUTICOLA  D.G. Mann"                                          , fixed_name = "Luticola"    , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "STAUROSIRA  (C.G. Ehrenberg) D.M. Williams & F.E. Round"      , fixed_name = "Staurosira"  , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "DIADESMIS  F.T. Kützing"                                      , fixed_name = "Diadesmis"   , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "PLANOTHIDIUM Round & Bukhtiyarova"                            , fixed_name = "Achnanthes conspicua", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "PLACONEIS  C. Mereschkowsky"                                  , fixed_name = "Placoneis", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "CYCLOSTEPHANOS  F.E. Round"                                   , fixed_name = "Cyclostephanos", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "ENTOMONEIS  C.G. Ehrenberg"                                   , fixed_name = "Entomoneis"   , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "RHOPALODIA  O Müller"                                         , fixed_name = "Rhopalodia"   , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "HANTZSCHIA  A. Grunow"                                        , fixed_name = "Hantzschia"   , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "CAMPYLODISCUS C.G.  Ehrenberg ex F.T. Kützing"                , fixed_name = "Campylodiscus", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "MERIDION  C.A. Agardh"                                        , fixed_name = "Meridion"   , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "MASTOGLOIA  G.H.K. Thwaites ex W. Smith 1856"                 , fixed_name = "Mastogloia" , data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "ANOMOEONEIS  E. Pfitzer 1871"                                 , fixed_name = "Anomoeoneis", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "TETRACYCLUS  J. Ralfs"                                        , fixed_name = "Tetracyclus", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "STAUROSIRELLA  D.M. Williams & F.E. Round  emend Morales"     , fixed_name = "Staurosirella", data_from = taxontable, data_to = taxontable)
taxontable <- dfm$append_to_tt(original_name = "NUPELA W. Vyverman & P. Compere"                              , fixed_name = "Nupela", data_from = taxontable, data_to = taxontable)

taxontable <- dfm$new_entry(ori = "CYMBELLOPSIS Krammer"                                         , fix = "Cymbellopsis", spe = NA, gen = "Cymbellopsis", tt = taxontable, tt_a = taxontable)
taxontable <- new_genus(ori = "AULISCUS  C.G. Ehrenberg"                                     , fix = "Auliscus", spe = NA, gen = "Auliscus", fam = "Eupodiscaceae", ord = "Eupodiscales", cla = "Mediophyceae")
taxontable <- new_genus(ori = "Ephemera bjoernoeyaensis Witkowski Metzeltin & Lange-Bertalot", fix = "Ephemera bjoernoeyaensis", spe = "Ephemera bjoernoeyaensis", gen = "Ephemera", fam = "Plagiotropidaceae", ord = "Naviculales", cla = "Bacillariophyceae")
saveRDS(taxontable, "data/diatoms/2022-05-17_taxontable_diatoms.rds")
