## what is the most similar in in taxontable 
strdist_id  <- amatch(TU, taxontable$original_name, maxDist = 100000)
strdist_tbl <- data.table(taxontable_name = taxontable$original_name[strdist_id], TU) |> 
        filter(!is.na(taxontable_name)) 

for (i in 1:nrow(strdist_tbl)){
        
        i.1 <- pull(strdist_tbl[i,1])
        i.2 <- pull(strdist_tbl[i,2])
        
        print(i.1)
        print(i.2)
        
        i.bool <- readline("match?:")
        
        if (i.bool == "y"){
                taxontable <- append_to_tt(i.1,i.2)
        } else if (i.bool == "n") {
                next()
        }
        rm(list = ls()[grepl("^i", ls())])
}

taxontable = taxontable[!original_name %in% c("Diadesmis gallica var. perpusilla", 
                                              "Luticola mutica var. ventricosa" 
)]

TU <- unique(data$taxon) |> sort()
TU <- setdiff(TU, taxontable$original_name)

## check against fwb table 
for (i in seq_along(TU)){
        i.tu  <- TU[i]
        if(check_fwb(i.tu)){
                x <- get_fwb(i.tu)
                taxontable <- add_entry_tt(x)
        }
        rm(i.tu)
}; rm(i)

TU <- unique(data$taxon) |> sort()
TU <- setdiff(TU, taxontable$original_name)

for (i in seq_along(TU)) {
        i.tu  <- TU[i]
        i.det <- str_detect(dia2$taxon, i.tu)
        if (any(i.det)) {
                i.id <- which(i.det)
                print(paste("name:", i.tu))
                print(paste("suggestions:", dia2$taxon[i.id]))
                i.rl <- readline()
        } else {
                i.id <- amatch(i.tu, dia2$taxon, maxDist = 100000) 
                if (is.null(i.id))
                        next()
                print(paste("name:", i.tu))
                print(paste("suggestions:", dia2$taxon[i.id]))
                i.rl <- readline()
        }        
        if (i.rl != "break") {
                i.id <- i.id[as.numeric(i.rl)]
                ## is it a synonym?
                if (!is.na(dia2$new[i.id])) {
                        print(paste("new code:",
                                    dia2$new[i.id]))
                        ## enter new code
                        i.rl2 <- readline()
                        i.id <- which(dia2$code == i.rl2)
                }
                print(paste("Final name: ", dia2$taxon[i.id]))
                i.final <- readline()
                ## check that against fwb
                if (check_fwb(i.final)) {
                        i.final <- get_fwb(i.final)
                }
                taxontable <- add_entry_tt(i.final)
        }
        rm(list = ls()[grepl(pattern = "^i\\.", x = ls())])
}

TU <- unique(data$taxon) |> sort()
TU <- setdiff(TU, taxontable$original_name)

taxontable <- new_entry("ACHNANTHES J.B.M. Bory de St. Vincent", fix = "Achnanthes", spe = NA, gen = "Achnanthes")
taxontable <- new_entry("AMPHORA  C.G. Ehrenberg ex F.T. Kützing", fix = "Amphora", spe = NA, gen = "Amphora")
taxontable <- new_entry("AULACOSEIRA  G.H.K. Thwaites", fix = "Aulacoseira", spe = NA, gen = "Aulacoseira")
taxontable <- new_entry("COCCONEIS  C.G. Ehrenberg", fix = "Cocconeis", spe = NA, gen = "Cocconeis")
taxontable <- new_entry("CYCLOTELLA  F.T. Kützing ex A de Brébisson", fix = "Cyclotella", spe = NA, gen = "Cyclotella")
taxontable <- new_entry("DIATOMA  J.B.M. Bory de St. Vincent", fix = "Diatoma", spe = NA, gen = "Diatoma")
taxontable <- new_entry("EPITHEMIA  F.T. Kützing", fix = "Epithemia", spe = NA, gen = "Epithemia")
taxontable <- new_entry("FRAGILARIA  H.C. Lyngbye", fix = "Fragilaria", spe = NA, gen = "Fragilaria")
taxontable <- new_entry("GYROSIGMA  A. Hassall", fix = "Gyrosigma", spe = NA, gen = "Gyrosigma")
taxontable <- new_entry("SKELETONEMA  R.K. Greville", fix = "Skeletonema", spe = NA, gen = "Skeletonema")
taxontable <- new_entry("STAURONEIS  C.G. Ehrenberg", fix = "Stauroneis", spe = NA, gen = "Stauroneis")
taxontable <- new_entry("STEPHANODISCUS  C.G. Ehrenberg", fix = "Stephanodiscus", spe = NA, gen = "Stephanodiscus")
taxontable <- new_entry("SYNEDRA  C.G. Ehrenberg", fix = "Synedra", spe = NA, gen = "Synedra")
taxontable <- new_entry("TABELLARIA  C.G. Ehrenberg", fix = "Tabellaria", spe = NA, gen = "Tabellaria")

TU <- unique(data$taxon) |> sort()
TU <- setdiff(TU, taxontable$original_name)

saveRDS(taxontable, paste0("data/diatoms/",Sys.Date(),"_taxontable_diatoms.rds"))

taxontable[species == "Pinnularia rabenhorstii", c("fixed_name", "species", "genus", "family") := .("Navicula rabenhorstii", "Navicula rabenhorstii", "Navicula", "Naviculaceae")]

TU[301:418]

taxontable <- new_entry("Pinnularia appendiculata var. irrorata", fix = "Pinnularia appenticulata-perirrorata-silvatica")
taxontable <- new_entry("Pinnularia borealis var. sublinearis", fix = "Pinnularia alpina-lata-borealis complex")
taxontable <- new_entry("Pinnularia brevistriata", fix = "Pinnularia brevistriata")
taxontable <- new_entry("Pinnularia decrescens var. rhombarea", fix = "Pinnularia divergens complex")
taxontable <- new_entry("Pinnularia divergentissima var. ardnamurchan", fix = "Pinnularia divergens complex")
taxontable <- new_entry("Pinnularia frauenbergiana var. caloneiopsis", fix = "Pinnularia frauenbergiana")
taxontable <- new_entry("Pinnularia lata f. thuringiaca", fix = "Navicula rabenhorstii")
taxontable <- new_entry("Pinnularia marchica var. marchica", fix = "Pinnularia marchica")
taxontable <- new_entry("Pinnularia marchica var. subrostrata", fix = "Pinnularia marchica")
taxontable <- new_entry("Pinnularia martinii", fix = "Pinnularia", spe = NA, gen = "Pinnularia")
taxontable <- new_entry("Pinnularia montana", fix = "Pinnularia montana")
taxontable <- new_entry("Pinnularia neomajor var. frequentis", fix = "Pinnularia maior Complex")
taxontable <- new_entry("Pinnularia peragallii", fix = "Pinnularia", spe = NA, gen = "Pinnularia")
taxontable <- new_entry("Pinnularia pertriundulata", fix = "Pinnularia pertriundulata")
taxontable <- new_entry("Pinnularia polyonca var. stidolphii", fix = "Pinnularia", spe = NA, gen = "Pinnularia")
taxontable <- new_entry("Pinnularia rhombarea var. variarea", fix = "Pinnularia rhombarea")
taxontable <- new_entry("Pinnularia ruttneri var. lauenburgiana", fix = "Pinnularia ruttneri")
taxontable <- new_entry("Pinnularia saprotolerans", fix = "Pinnularia saprotolerans")
taxontable <- new_entry("Pinnularia similis f. recta", fix = "Pinnularia similis")
taxontable <- new_entry("Pinnularia sinistra var. sublanceolata", fix = "Pinnularia sinistra")
taxontable <- new_entry("Pinnularia stomatophora var. triundulata", fix = "Pinnularia graciloides")
taxontable <- new_entry("Pinnularia subaldenii", fix = "Pinnularia subaldenii")
taxontable <- new_entry("Pinnularia subrupestris var. cuneata", fix = "Pinnularia", spe = NA, gen = "Pinnularia")
taxontable <- new_entry("Pinnularia sudetica var. sudetica", fix = "Pinnularia", spe = NA, gen = "Pinnularia")
taxontable <- new_entry("Pinnularia tirolensis var. tirolensis", fix = "Pinnularia tirolensis")
taxontable <- new_entry("Pinnularia viridis var. viridis morphotype 1", fix = "Pinnularia viridis complex")
taxontable <- new_entry("Pinnularia viridis var. viridis morphotype 2", fix = "Pinnularia viridis complex")
taxontable <- new_entry("Placoneis clementispronina", fix = "Placoneis clementispronina")
taxontable <- new_entry("Placoneis nanoclementi", fix = "Placoneis nanoclementi")
taxontable <- new_entry("Placoneis parvapolonica", fix = "Placoneis parvapolonica")
taxontable <- new_genus("Plagiotropis tayrecta", fix = "Plagiotropis tayrecta", spe = "Plagiotropis tayrecta", gen = "Plagiotropis", fam = "Plagiotropidaceae", ord = "Naviculales", cla = "Bacillariophyceae")
taxontable <- new_entry("Planothidium abbreviatum", fix = "Planothidium abbreviatum")
taxontable <- new_entry("Planothidium amphibium", fix = "Planothidium amphibium")
taxontable <- new_entry("Planothidium frequentissimum abnormal form", fix = "Planothidium lanceolatum")
taxontable <- new_entry("Planothidium hauckianum var. rostrata", fix = "Planothidium delicatulum")
taxontable <- new_entry("Planothidium minusculum", fix = "Achnanthes minuscula")
taxontable <- new_entry("Planothidium pumilum", fix = "Planothidium pumilum")
taxontable <- new_entry("Planothidium rostrolanceolatum", fix = "Planothidium rostrolanceolatum")
taxontable <- new_entry("Planothidium victori", fix = "Planothidium victorii")
taxontable <- new_entry("Planothidium werumianum", fix = "Planothidium werumianum")
taxontable <- new_entry("Platessa saxonica", fix = "Platessa saxonica")
taxontable <- new_entry("Pleurosira laevis f. laevis", fix = "Pleurosira laevis")
taxontable <- new_genus("Pravifusus", fix = "Pravifusus", spe = NA, gen = "Pravifusus", fam = "Bacillariophyta familia incertae sedis", ord = "Bacillariophyta ordo incertae sedis", cla = "Bacillariophyta classis incertae sedis")
taxontable <- new_entry("Prestauroneis protracta", fix = "Prestauroneis protracta")
taxontable <- new_entry("Prestauroneis protractoides", fix = "Prestauroneis protractoides")
taxontable <- new_genus("Proboscia praebarboi", fix = "Proboscia praebarboi", spe = "Proboscia praebarboi", gen = "Proboscia", fam = "Probosciaceae", ord = "Rhizosoleniales", cla = "Coscinodiscophyceae")
taxontable <- new_genus("Protoraphis hustedtiana", fix = "Protoraphis hustedtiana", spe = "Protoraphis hustedtiana", gen = "Protoraphis", fam = "Protoraphidaceae", ord = "Protoraphidales", cla = "Bacillariophyceae")
taxontable <- new_entry("Pseudofallacia", fix = "Pseudofallacia", spe = NA, gen = "Pseudofallacia")
taxontable <- new_entry("Pseudostaurosira (as Punctastriata) subconstricta", fix = "Pseudostaurosira subconstricta")
taxontable <- new_entry("Pseudostaurosira brevistriata abnormal form", fix = "Pseudostaurosira brevistriata complex")
taxontable <- new_entry("Pseudostaurosira cataractarum", fix = "Nanofrustulum cataractarum")
taxontable <- new_entry("Pseudostaurosira microstriata var. microstriata", fix = "Pseudostaurosira microstriata")
taxontable <- new_genus("Pseudostaurosiropsis", fix = "Pseudostaurosiropsis", spe = NA, gen = "Pseudostaurosiropsis", fam = "Staurosiraceae", ord = "Fragilariales", cla = "Bacillariophyceae")
taxontable <- new_entry("Pseudostaurosiropsis connecticutensis", fix = "Pseudostaurosiropsis connecticutensis")
taxontable <- new_entry("Pseudostaurosiropsis geocollegarum", fix = "Pseudostaurosiropsis geocollegarum")
taxontable <- new_entry("Pseudostaurosiropsis geocollegarum f. triradiatum", fix = "Pseudostaurosiropsis geocollegarum")
taxontable <- new_genus("Rhabdonema", fix = "Rhabdonema", spe = NA, gen = "Rhabdonema", fam = "Rhabdonemataceae", ord = "Rhabdonematales", cla = "Bacillariophyceae")
taxontable <- new_entry("Rhaphoneis", fix = "Rhaphoneis", spe = NA, gen = "Rhaphoneis")
taxontable <- new_entry("Sellaphora absoluta", fix = "Sellaphora absoluta")
taxontable <- new_entry("Sellaphora bacillum var. lepida", fix = "Sellaphora laevissima Complex")
taxontable <- new_entry("Sellaphora bosniaca", fix = "Sellaphora bosniaca")
taxontable <- new_entry("Sellaphora cosmopolitana", fix = "Sellaphora cosmopolitana")
taxontable <- new_entry("Sellaphora crassulexigua", fix = "Sellaphora crassulexigua")
taxontable <- new_entry("Sellaphora difficillima", fix = "Sellaphora difficillima")
taxontable <- new_entry("Sellaphora labernardierei", fix = "Sellaphora labernardierei")
taxontable <- new_entry("Sellaphora nigri", fix = "Sellaphora nigri")
taxontable <- new_entry("Sellaphora rhombelliptica", fix = "Sellaphora rhombelliptica")
taxontable <- new_entry("Sellaphora ruttneri", fix = "Sellaphora ruttneri")
taxontable <- new_entry("Sellaphora saprotolerans", fix = "Sellaphora saprotolerans")
taxontable <- new_entry("Sellaphora schaumburgii", fix = "Sellaphora schaumburgii")
taxontable <- new_entry("Sellaphora utermoehlii", fix = "Sellaphora utermoehlii")
taxontable <- new_entry("Seminavis insignis", fix = "Seminavis insignis")
taxontable <- new_genus("Sieminskia wohlenbergii", fix = "Sieminskia wohlenbergii", spe = "Sieminskia wohlenbergii", gen = "Sieminskia", fam = "Naviculales incertae sedis", ord = "Naviculales", cla = "Bacillariophyceae")
taxontable <- new_genus("Stauroforma", fix = "Stauroforma", spe = NA, gen = "Stauroforma", fam = "Staurosiraceae", ord = "Fragilariales", cla = "Bacillariophyceae")
taxontable <- new_entry("Stauroforma atomus", fix = "Martyana atomus")
taxontable <- new_entry("Stauroneis anceps var. abnormis", fix = "Stauroneis anceps Complex")
taxontable <- new_entry("Stauroneis siberica var. siberica", fix = "Stauroneis anceps Complex")
taxontable <- new_entry("Stauroneis thermicola f. lanceolata", fix = "Stauroneis complex small")
taxontable <- new_genus("Stauronella indubitabilis", fix = "Craspedostauros indubitabilis", spe = "Craspedostauros indubitabilis", gen = "Craspedostauros", fam = "Mastogloiaceae", ord = "Mastogloiales", cla = "Bacillariophyceae")
taxontable <- new_genus("Staurophora tackei", fix = "Staurophora tackei", spe = "Staurophora tackei", gen = "Staurophora", fam = "Anomoeoneidaceae", ord = "Cymbellales", cla = "Bacillariophyceae")
taxontable <- new_entry("Staurophora wislouchii", fix = "Staurophora wislouchii")
taxontable <- new_entry("Staurosira construens f. subsalina", fix = "Pseudostaurosira subsalina")
taxontable <- new_entry("Staurosira longwanensis", fix = "Staurosira longwanensis")
taxontable <- new_entry("Staurosira parasitoides", fix = "Pseudostaurosira parasitoides")
taxontable <- new_entry("Staurosira pottiezii", fix = "Staurosira pottiezii")
taxontable <- new_entry("Staurosira pseudoconstruens var. trigona", fix = "Fragilaria construens-pseudoconstruens")
taxontable <- new_entry("Staurosirella grunowii", fix = "Staurosirella grunowii")
taxontable <- new_entry("Staurosirella krammeri", fix = "Staurosirella krammeri")
taxontable <- new_entry("Staurosirella pinnata abnormal form", fix = "Staurosirella pinnata complex")
taxontable <- new_entry("Stephanodiscus minutus", fix = "Cyclotella tanakae")
taxontable <- new_entry("Surirella alicula", fix = "Surirella alicula")
taxontable <- new_entry("Surirella brebissonii abnormal form", fix = "Surirella brebissonii")
taxontable <- new_entry("Surirella brebissonii var. punctata", fix = "Surirella brebissonii")
taxontable <- new_entry("Surirella capronii var. reducta", fix = "Surirella capronii")
taxontable <- new_entry("Surirella lange-bertalotii", fix = "Surirella lange-bertalotii")
taxontable <- new_entry("Surirella librile", fix = "Surirella librile")
taxontable <- new_entry("Surirella nervosa", fix = "Surirella splendida-tenera")
taxontable <- new_entry("Surirella undulata", fix = "Surirella undulata")
taxontable <- new_entry("Surirella vandevijveri", fix = "Surirella vandevijveri")
taxontable <- new_entry("Synedra delicatissima var. angustissima", fix = "Fragilaria tenera complex")
taxontable <- new_entry("Synedra rumpens var. familiaris", fix = "Fragilaria capucina complex")
taxontable <- new_entry("Synedra tabulata var. obtusa", fix = "Tabularia tabulata")
taxontable <- new_entry("Synedra ulna var. spathulifera", fix = "Ulnaria ulna complex")
taxontable <- new_entry("Synedra vaucheriae var. capitellata", fix = "Fragilaria capucina complex")
taxontable <- new_entry("Tabellaria flocculosa abnormal form", fix = "Tabellaria flocculosa Complex")
taxontable <- new_genus("Thalassiocyclus lucens", fix = "Thalassiocyclus lucens", spe = "Thalassiocyclus lucens", gen = "Thalassiocyclus", fam = "Thalassiosiraceae", ord = "Thalassiosirales", cla = "Mediophyceae")
taxontable <- new_genus("Trachyneis aspera", fix = "Trachyneis", spe = NA, gen = "Trachyneis", fam = "Naviculaceae", ord = "Naviculales", cla = "Bacillariophyceae")
taxontable <- new_genus("Trachysphenia acuminata", fix = "Trachysphenia acuminata", spe = "Trachysphenia acuminata", gen = "Trachysphenia", fam = "Ulnariaceae", ord = "Licmophorales", cla = "Bacillariophyceae")
taxontable <- new_entry("Trachysphenia australis var. australis", fix = "Trachysphenia australis")
taxontable <- new_genus("Triceratium", fix = "Triceratium", spe = NA, gen = "Triceratium", fam = "Triceratiaceae", ord = "Triceratiales", cla = "Coscinodiscophyceae")
taxontable <- new_entry("Tryblionella compressa", fix = "Tryblionella compressa")
taxontable <- new_entry("Tryblionella hantzschiana", fix = "Tryblionella hantzschiana")
taxontable <- new_entry("Tryblionella kuetzingii", fix = "Tryblionella", spe = NA, gen = "Tryblionella")
taxontable <- new_entry("Ulnaria grunowii", fix = "Ulnaria grunowii")
taxontable <- new_entry("Ulnaria ulna abnormal form", fix = "Ulnaria ulna complex")
taxontable <- new_genus("Vikingea promunturii", fix = "Vikingea", spe = "Vikingea promunturii", gen = "Vikingea", fam = "Cocconeidaceae", ord = "Cocconeidales", cla = "Bacillariophyceae")

taxontable <- new_entry("Nitzschia paleacea abnormal form", fix = "Nitzschia palea-paleacea")
taxontable <- new_entry("Nitzschia paleacea f. acicularioides", fix = "Nitzschia palea-paleacea")
taxontable <- new_entry("Nitzschia recta abnormal form", fix = "Nitzschia dissipata-recta Complex")
taxontable <- new_entry("Nitzschia recta var. rectiformis", fix = "Nitzschia dissipata-recta Complex")
taxontable <- new_entry("Nitzschia recta var. robusta", fix = "Nitzschia dissipata-recta Complex")
taxontable <- new_entry("Nitzschia rhombicolancettula", fix = "Nitzschia rhombicolancettula")
taxontable <- new_entry("Nitzschia sigma var. diminuta", fix = "Nitzschia sigma Complex")
taxontable <- new_entry("Nitzschia subtilis f. tchadensis", fix = "Nitzschia", spe = NA, gen = "Nitzschia")
taxontable <- new_entry("Nitzschia tryblionella var. salinarum", fix = "Nitzschia", spe = NA, gen = "Nitzschia")
taxontable <- new_entry("Nitzschia vixpalea", fix = "Nitzschia vixpalea")
taxontable <- new_genus("Nitzschiellae", fix = "Nitzschiella", spe = NA, gen = "Nitzschiella", fam = "Bacillariaceae", ord = "Bacillariales", cla = "Bacillariophyceae")
taxontable <- new_entry("Nupela subrostrata", fix = "Nupela subrostrata")
taxontable <- new_genus("Odontella", fix = "Odontella", spe = NA, gen = "Odontella", fam = "Odontellaceae", ord = "Eupodiscales", cla = "Mediophyceae")
taxontable <- new_entry("Odontella aurita", fix = "Odontella aurita")
taxontable <- new_entry("Odontidium", fix = "Odontidium", spe = NA, gen = "Odontidium")
taxontable <- new_entry("Odontidium neomaximum", fix = "Odontidium neomaximum")
taxontable <- new_entry("Odontidium tabellaria", fix = "Staurosira tabellaria")
taxontable <- new_genus("Orthoneis", fix = "Orthoneis", spe = NA, gen = "Orthoneis", fam = "Bacillariophyta familia incertae sedis", ord = "Bacillariophyta ordo incertae sedis", cla = "Bacillariophyta classis incertae sedis")
taxontable <- new_entry("Pantocsekiella", fix = "Pantocsekiella", spe = NA, gen = "Pantocsekiella")
taxontable <- new_entry("Pantocsekiella comensis", fix = "Pantocsekiella comensis")
taxontable <- new_entry("Pantocsekiella costei", fix = "Pantocsekiella costei")
taxontable <- new_entry("Pantocsekiella delicatula", fix = "Pantocsekiella delicatula")
taxontable <- new_entry("Pantocsekiella ocellata", fix = "Pantocsekiella ocellata")
taxontable <- new_entry("Pantocsekiella polymorpha", fix = "Pantocsekiella polymorpha")
taxontable <- new_entry("Pantocsekiella wuethrichiana", fix = "Pantocsekiella wuethrichiana")

taxontable <- new_entry("Navicula tuscula var. stroesei", fix = "Aneumastus stroesei")
taxontable <- new_entry("Navicula upsaliensis ssp. baicalupsaliensis", fix = "Navicula cryptotenella/cryptotenelloides")
taxontable <- new_entry("Naviculadicta seminula", fix = "Eolimna minima-seminulum-atomoidess")
taxontable <- new_genus("Navigeia paludosa", fix = "Navigeia paludosa", spe = "Navigeia paludosa", gen = "Navigeia", fam = "Bacillariophyta familia incertae sedis", ord = "Bacillariophyta ordo incertae sedis", cla = "Bacillariophyta classis incertae sedis")
taxontable <- new_entry("Navigiolum", fix = "Navigiolum", spe = NA, gen = "Navigiolum")
taxontable <- new_entry("Neidium dubium var. cuneata", fix = "Neidium dubium Complex")
taxontable <- new_entry("Neidium hustedtii var. ellipticum", fix = "Neidium hustedtii")
taxontable <- new_entry("Neidium productum var. minor", fix = "Neidium productum Complex")
taxontable <- new_entry("Nitzschia acicularis var. closterioides", fix = "Nitzschia acicularis Complex")
taxontable <- new_entry("Nitzschia actinastroides var. ligeriensis", fix = "Nitzschia fruticosa")
taxontable <- new_entry("Nitzschia amphibia var. pelagica", fix = "Nitzschia natans")
taxontable <- new_entry("Nitzschia bertrandii", fix = "Nitzschia bertrandii")
taxontable <- new_entry("Nitzschia bremensis var. brunswigensis", fix = "Nitzschia bremensis")
taxontable <- new_entry("Nitzschia dissipata abnormal form", fix = "Nitzschia dissipata-recta Complex")
taxontable <- new_entry("Nitzschia fonticola abnormal form", fix = "Nitzschia fonticola Complex")
taxontable <- new_entry("Nitzschia frustulum var. minutula", fix = "Nitzschia frustulum Complex")
taxontable <- new_entry("Nitzschia levidensis var. victoriae", fix = "Tryblionella victoriae")
taxontable <- new_entry("Nitzschia ligowskii", fix = "Nitzschia ligowskii")
taxontable <- new_entry("Nitzschia littoralis var. littoralis", fix = "Tryblionella", spe = NA, gen = "Tryblionella")
taxontable <- new_entry("Nitzschia lorenziana var. incurva", fix = "Nitzschia lorenziana")
taxontable <- new_entry("Nitzschia lorenziana var. subtilis", fix = "Nitzschia lorenziana")
taxontable <- new_entry("Nitzschia microcephala var. elegantula", fix = "Nitzschia elegantula")
taxontable <- new_entry("Nitzschia minuscula", fix = "Nitzschia minuscula")
taxontable <- new_entry("Nitzschia palea var. tropica", fix = "Nitzschia palea-paleacea")
taxontable <- new_entry("Nitzschia paleacea abnormal form", fix = "Nitzschia palea-paleacea")

taxontable <- new_genus("Muelleria", fix = "Muelleria", spe = NA, gen = "Muelleria", fam = "Neidiaceae", ord = "Naviculales", cla = "Bacillariophyceae")
taxontable <- new_entry("Navicula arenaria var. rostellata", fix = "Navicula lanceolata complex")
taxontable <- new_entry("Navicula bulnheimii", fix = "Proschkinia longirostris")
taxontable <- new_entry("Navicula cuspidata f. craticula", fix = "Craticula", spe = NA, gen = "Craticula")
taxontable <- new_entry("Navicula elaphros", fix = "Navicula elaphros")
taxontable <- new_entry("Navicula hanseatica ssp. circumarctica", fix = "Navicula hanseatica")
taxontable <- new_entry("Navicula hanseatica ssp. hanseatica", fix = "Navicula hanseatica")
taxontable <- new_entry("Navicula hochstetteri var. patagonica", fix = "Navicula hochstetteri")
taxontable <- new_entry("Navicula ireneae", fix = "Navicula ireneae")
taxontable <- new_entry("Navicula johncarterii", fix = "Navicula johncarterii")
taxontable <- new_entry("Navicula meulemansii", fix = "Navicula meulemansii")
taxontable <- new_entry("Navicula mutica f. densestriata", fix = "Luticola Complex", spe = NA, gen = "Luticola")
taxontable <- new_entry("Navicula peregrina var. elliptica", fix = "Navicula aurora-peregrina-reinhardtii++")
taxontable <- new_entry("Navicula perlucida f. angustata", fix = "Naviculadicta angustata")
taxontable <- new_entry("Navicula pupula f. rostrata", fix = "Sellaphora pupula Complex")
taxontable <- new_entry("Navicula pupula var. aquaeductae", fix = "Sellaphora pupula Complex")
taxontable <- new_entry("Navicula pusilla var. capitata", fix = "Cosmioneis pusilla")
taxontable <- new_entry("Navicula recens abnormal form", fix = "Navicula recens")
taxontable <- new_entry("Navicula reichardtiana abnormal form", fix = "Navicula reichardtiana-caterva")
taxontable <- new_entry("Navicula rhynchocephala var. germainii", fix = "Navicula germainii")
taxontable <- new_entry("Navicula ruttneri var. capitata", fix = "Navicula ruttneri")
taxontable <- new_entry("Navicula salinarum var. intermedia", fix = "Navicula capitatoradiata")
taxontable <- new_entry("Navicula seminulum var. radiosa", fix = "Eolimna minima-seminulum-atomoides")
taxontable <- new_entry("Navicula trivialis var. trivialis", fix = "Navicula trivialis-salinarum")
taxontable <- new_entry("Navicula trophicatrix ssp. vixtrophicatrix", fix = "Navicula trophicatrix")

taxontable <- new_entry("Iconella", fix = "Iconella", spe = NA, gen = "Iconella") 
taxontable <- new_entry("Iconella bifrons", fix = "Iconella bifrons") 
taxontable <- new_entry("Iconella curvula", fix = "Iconella curvula") 
taxontable <- new_entry("Iconella hibernica", fix = "Iconella hibernica") 
taxontable <- new_entry("Iconella linearis", fix = "Iconella linearis") 
taxontable <- new_entry("Iconella robusta", fix = "Iconella robusta") 
taxontable <- new_entry("Karayevia ploenensis abnormal form", fix = "Karayevia ploenensis") 
taxontable <- new_genus("Kobayasia", fix = "Kobayasia", spe = NA, gen = "Kobayasia", fam = "Naviculaceae", ord = "Naviculales", cla = "Bacillariophyceae") 
taxontable <- new_genus("Kurtkrammeria aequalis", fix = "Kurtkrammeria aequalis", spe = "Kurtkrammeria aequalis", gen = "Kurtkrammeria", fam = "Cymbellaceae", ord = "Cymbellales", cla = "Bacillariophyceae") 
taxontable <- new_genus("Lemnicola exigua", fix = "Gogorevia exilis", spe = "Gogorevia exilis", gen = "Gogorevia", fam = "Achnanthidiaceae", ord = "Cocconeidales", cla = "Bacillariophyceae") 
taxontable <- new_entry("Licmophora", fix = "Licmophora", spe = NA, gen = "Licmophora") 
taxontable <- new_entry("Lindavia austriaca", fix = "Lindavia austriaca") 
taxontable <- new_entry("Lindavia bodanica", fix = "Lindavia bodanica complex") 
taxontable <- new_entry("Lindavia costei", fix = "Pantocsekiella costei") 
taxontable <- new_entry("Lindavia praetermissa", fix = "Lindavia praetermissa") 
taxontable <- new_entry("Lindavia tenuistriata", fix = "Lindavia tenuistriata") 
taxontable <- new_entry("Luticola frequentissima", fix = "Luticola frequentissima") 
taxontable <- new_entry("Luticola hlubikovae", fix = "Luticola hlubikovae") 
taxontable <- new_entry("Luticola incana", fix = "Luticola incana") 
taxontable <- new_entry("Luticola mutica var. ventricosa", fix = "Luticola ventricosa") 
taxontable <- new_entry("Mayamaea cavernicola", fix = "Mayamaea cavernicola") 
taxontable <- new_entry("Melosira japonica", fix = "Aulacoseira ambigua") 
taxontable <- new_genus("Mesodictyopsis media", fix = "Mesodictyopsis media", spe = "Mesodictyopsis media", gen = "Mesodictyopsis" ,fam = "Stephanodiscaceae", ord = "Stephanodiscales", cla = "Mediophyceae") 
taxontable <- new_entry("Microcostatus", fix = "Microcostatus", spe = NA, gen = "Microcostatus") 
taxontable <- new_genus("Minidiscus proschkinae", fix = "Minidiscus proschkinae", spe = "Minidiscus proschkinae", gen = "Minidiscus", fam = "Thalassiosiraceae", ord = "Thalassiosirales", cla = "Mediophyceae") 

taxontable <- new_entry("Gomphonema bohemicum ssp. angustiminus", fix = "Gomphonema bohemicum")
taxontable <- new_entry("Gomphonema bohemicum ssp. bohemicum", fix = "Gomphonema bohemicum")
taxontable <- new_entry("Gomphonema brasiliense subsp. pacificum", fix = "Gomphonema brasiliense")
taxontable <- new_entry("Gomphonema campodunense", fix = "Gomphonema campodunense")
taxontable <- new_entry("Gomphonema exiguum var. platypus", fix = "Gomphonemopsis exigua")
taxontable <- new_entry("Gomphonema frickei var. andina", fix = "Gomphonema frickei")
taxontable <- new_entry("Gomphonema gracile var. clavicula", fix = "Gomphonema gracile complex")
taxontable <- new_entry("Gomphonema gracile var. naviculoides", fix = "Gomphonema gracile complex")
taxontable <- new_entry("Gomphonema graciledictum", fix = "Gomphonema graciledictum")
taxontable <- new_entry("Gomphonema lanceolatum var. acutiuscula", fix = "Gomphonema lanceolatum")
taxontable <- new_entry("Gomphonema linearoides", fix = "Gomphonella linearoides")
taxontable <- new_entry("Gomphonema manifestum", fix = "Gomphonema manifestum")
taxontable <- new_entry("Gomphonema micropus abnormal form", fix = "Gomphonema micropus Complex")
taxontable <- new_entry("Gomphonema micropus morphotyp elongatum", fix = "Gomphonema micropus Complex")
taxontable <- new_entry("Gomphonema minutum abnormal form", fix = "Gomphonema", spe = NA, gen = "Gomphonema")
taxontable <- new_entry("Gomphonema olivaceum abnormal form", fix = "Gomphonema olivaceum/olivaceoides")
taxontable <- new_entry("Gomphonema pulvillum", fix = "Gomphonema pulvillum")
taxontable <- new_entry("Gomphonema sichuanensis", fix = "Gomphonema sichuanenese")
taxontable <- new_entry("Gomphonema subclavata var. montanum", fix = "Gomphonema clavatum")
taxontable <- new_entry("Gomphonema vibrio var. bohemicum", fix = "Gomphonema vibrio")
taxontable <- new_entry("Grunowia tabellaria", fix = "Grunowia tabellaria")
taxontable <- new_entry("Halamphora pertusa", fix = "Halamphora pertusa")
taxontable <- new_entry("Hantzschia amphioxys f. capitata", fix = "Hantzschia amphioxys")
taxontable <- new_entry("Humidophila", fix = "Humidophila", spe = NA, gen = "Humidophila")

taxontable <- new_entry("Achnanthes clevei var. bottnica", fix = "Karayevia clevei")
taxontable <- new_entry("Achnanthes exigua var. constricta", fix = "Achnanthidium exigua/ziegleri/subexigua")
taxontable <- new_entry("Achnanthes exigua var. elliptica", fix = "Achnanthidium exigua/ziegleri/subexigua")
taxontable <- new_entry("Achnanthes flexella var. alpestris", fix = "Eucocconeis laevis/alpestris")
taxontable <- new_entry("Achnanthes helvetica var. minor", fix = "Psammothidium helveticum/chlidanos/daonense")
taxontable <- new_entry("Achnanthes imperfecta", fix = "Achnanthes impexiformis")
taxontable <- new_entry("Achnanthes montana var. montana", fix = "Platessa montana")
taxontable <- new_entry("Achnanthes ploenensis var. gessneri", fix = "Kolbesia gessneri")
taxontable <- new_entry("Achnanthes pusilla var. crassa", fix = "Achnanthidium crassum" )
taxontable <- new_entry("Achnanthes ventralis var. crassa", fix = "Psammothidium ventrale Complex")
taxontable <- new_entry("Achnanthidium acsiae", fix = "Achnanthidium acsiae")
taxontable <- new_entry("Achnanthidium anastasiae", fix = "Achnanthidium anastasiae")
taxontable <- new_entry("Achnanthidium barbei", fix = "Achnanthidium barbei")
taxontable <- new_entry("Achnanthidium biasolettianum var. subatomus", fix = "Achnanthidium subatomus")
taxontable <- new_entry("Achnanthidium cf.gracillimum", fix = "Achnanthidium minutissimum")
taxontable <- new_entry("Achnanthidium exiguum abnormal form", fix = "Achnanthidium exigua/ziegleri/subexigua")
taxontable <- new_entry("Achnanthidium lusitanicum", fix = "Achnanthidium lusitanicum")
taxontable <- new_entry("Achnanthidium nanum", fix = "Achnanthidium nanum")
taxontable <- new_entry("Achnanthidium polonicum", fix = "Achnanthidium polonicum")
taxontable <- new_entry("Achnanthidium robustum", fix = "Achnanthidium robustum")
taxontable <- new_entry("Achnanthidium sieminskae", fix = "Achnanthidium sieminskae")
taxontable <- new_entry("Actinella", fix = "Actinella", spe = NA, gen = "Actinella")
taxontable <- new_entry("Actinocyclus determinatus", fix = "Actinocyclus determinatus")
taxontable <- new_genus("Actinodiscus", fix = "Actinodiscus", gen = "Actinodiscus", fam = "Heliopeltaceae", ord = "Coscinodiscales", cla = "Coscinodiscophyceae")
taxontable <- new_entry("Adlafia baicalensis", fix = "Adlafia baicalensis")

taxontable <- new_entry("Adlafia minuscula abnormal form", fix = "Navicula krasskei-egregia-minuscula")
taxontable <- new_entry("Amphora coffeaeformis var. dusenii", fix = "Halamphora dusenii")
taxontable <- new_entry("Amphora cymbaphora", fix = "Amphora cymbaphora")
taxontable <- new_entry("Amphora minutissima var. africana", fix = "Amphora minutissima")
taxontable <- new_entry("Amphora ostrearia var. vitrea", fix = "Halamphora coffeaeformis")
taxontable <- new_entry("Amphora ovalis abnormal form", fix = "Amphora ovalis")
taxontable <- new_entry("Amphora ovalis f. minor", fix = "Amphora ovalis")
taxontable <- new_entry("Amphora ovalis var. libyca", fix = "Halamphora montana")
taxontable <- new_entry("Anaulus", fix = "Anaulus", spe = NA, gen = "Anaulus")
taxontable <- new_entry("Anomoeoneis brachysira var. zellensis", fix = "Brachysira zellensis")
taxontable <- new_genus("Anorthoneis eurystoma", fix = "Anorthoneis eurystoma", spe = "Anorthoneis eurystoma", gen = "Anorthoneis", fam = "Cocconeidaceae", ord = "Cocconeidales", cla = "Bacillariophyceae")
taxontable <- new_genus("Aulacodiscus orientalis", fix = "Aulacodiscus orientalis", spe = "Aulacodiscus orientalis", gen = "Aulacodiscus", fam = "Aulacodiscaceae", ord = "Coscinodiscales", cla = "Coscinodiscophyceae")
taxontable <- new_genus("Aulacoseira brasiliensis", fix = "Aulacoseiraceae brasiliensis", spe = "Aulacoseiraceae brasiliensis", gen = "Aulacoseiraceae", fam = "Aulacoseiraceae", ord = "Aulacoseirales", cla = "Coscinodiscophyceae")
taxontable <- new_entry("Aulacoseira islandica subsp. helvetica", fix = "Aulacoseira islandica")
taxontable <- new_entry("Aulacoseira italica f. curvata", fix = "Aulacoseira italica complex")
taxontable <- new_genus("Austariella jamalinensis", fix = "Austariella jamalinensis", spe = "Austariella jamalinensis", gen = "Austariella", fam = "Naviculaceae", ord = "Naviculales", cla = "Bacillariophyceae")
taxontable <- new_entry("Brachysira calcicola ssp. pfisteri", fix = "Brachysira calcicola")
taxontable <- new_genus("Brassierea", fix = "Brassierea", gen = "Brassierea", fam = "Fragilariaceae", ord = "Fragilariales", cla = "Bacillariophyceae")
taxontable <- new_entry("Brevilinea kevei", fix = "Brevilinea kevei")
taxontable <- new_genus("Brockmanniella brockmannii", fix = "Brockmanniella brockmannii", spe = "Brockmanniella brockmannii", gen = "Brockmanniella", fam = "Cymatosiraceae", ord = "Cymatosirales", cla = "Mediophyceae")
taxontable <- new_entry("Caloneis langebertalotii", fix = "Caloneis langebertalotii")
taxontable <- new_entry("Caloneis paludosa", fix = "Caloneis paludosa")
taxontable <- new_entry("Caloneis schumanniana f. alaskaensis", fix = "Caloneis", spe = NA, gen = "Caloneis")
taxontable <- new_entry("Caloneis silicula var. bicuneata", fix = "Caloneis silicula Complex")
taxontable <- new_genus("Campyloneis grevillei", fix = "Campyloneis grevillei", spe = "Campyloneis grevillei", gen = "Campyloneis", fam = "Cocconeidaceae", ord = "Cocconeidales", cla = "Bacillariophyceae")

taxontable <- new_genus("Campylopyxis garkeana", fix = "Campylopyxis garkeana", spe = "Campylopyxis garkeana", gen = "Campylopyxis", fam = "Rhoicospheniaceae", ord = "Cymbellales", cla = "Bacillariophyceae")
taxontable <- new_genus("Campylostylus", fix = "Campylostylus", spe = NA, gen = "Campylostylus", fam = "Bacillariophyta familia incertae sedis", ord = "Bacillariophyta ordo incertae sedis", cla = "Bacillariophyta classis incertae sedis")
taxontable <- new_genus("Centroporus mirabilis", fix = "Centroporus mirabilis", spe = "Centroporus mirabilis", gen = "Centroporus", fam = "Heliopeltaceae", ord = "Coscinodiscales", cla = "Coscinodiscophyceae")
taxontable <- new_entry("Chamaepinnularia obsoleta", fix = "Chamaepinnularia obsoleta")
taxontable <- new_entry("Cocconeis disculus var. minor", fix = "Cocconeis neodiminuta")
taxontable <- new_entry("Cocconeis placentula var. baicalensis", fix = "Cocconeis baikalensis")
taxontable <- new_entry("Cocconeis placentula var. euglypta abnormal form", fix = "Cocconeis placentula")
taxontable <- new_entry("Cocconeis placentula var. euglyptoides", fix = "Cocconeis placentula")
taxontable <- new_entry("Cocconeis placentula var. lineata abnormal form", fix = "Cocconeis placentula")
taxontable <- new_genus("Coscinodiscus nodulifer", fix = "Azpeitia nodulifer", spe = "Azpeitia nodulifer", gen = "Azpeitia", fam = "Hemidiscaceae", ord = "Coscinodiscales", cla = "Coscinodiscophyceae")
taxontable <- new_genus("Craspedodiscus", fix = "Craspedodiscus", spe = NA, gen = "Craspedodiscus", fam = "Coscinodiscaceae", ord = "Coscinodiscales", cla = "Coscinodiscophyceae")
taxontable <- new_entry("Craticula cuspidata var. heribaudii", fix = "Craticula", spe = NA, gen = "Craticula")
taxontable <- new_entry("Craticula halophila f. tenuirostris", fix = "Craticula vixvisibilis")
taxontable <- new_entry("Ctenophora pulchella var. lacerata", fix = "Ctenophora pulchella")
taxontable <- new_entry("Cyclotella stelligera var. tenuis", fix = "Discostella", spe = NA, gen = "Discostella")
taxontable <- new_entry("Cymatoneis", fix = "Cymatoneis", spe = NA, gen = "Cymatoneis")
taxontable <- new_entry("Cymatopleura angulata", fix = "Cymatopleura angulata")
taxontable <- new_entry("Cymatosira", fix = "Cymatosira", spe = NA, gen = "Cymatosira")
taxontable <- new_entry("Cymbella affinis var. excisa", fix = "Cymbella affinis")
taxontable <- new_entry("Cymbella affinis var. neoprocera", fix = "Cymbella affinis")
taxontable <- new_entry("Cymbella amphicephala var. citrus", fix = "Cymbopleura citrus")
taxontable <- new_entry("Cymbella hustedtii var. compacta", fix = "Cymbella", spe = NA, gen = "Cymbella")
taxontable <- new_entry("Cymbella hybrida var. capitata", fix = "Cymbopleura", spe = NA, gen = "Cymbopleura")
taxontable <- new_entry("Cymbella laevis var. lata", fix = "Cymbella", spe = NA, gen = "Cymbella")
taxontable <- new_entry("Cymbella mexicana var. lata", fix = "Cymbella mexicana")
taxontable <- new_entry("Cymbella neocistula var. islandica", fix = "Cymbella cistula group", spe = "Cymbella cistula group", gen = "Cymbella")

taxontable <- new_entry("Cymbella neocistula var. neocistula", fix = "Cymbella cistula group")
taxontable <- new_entry("Cymbella neolanceolata var. bottnica", fix = "Cymbella neolanceolata")
taxontable <- new_entry("Cymbella proxima var. borealis", fix = "Cymbella cistula group")
taxontable <- new_entry("Cymbella vulgata var. plitvicensis", fix = "Cymbella vulgata")
taxontable <- new_entry("Cymbella vulgata var. vulgata", fix = "Cymbella vulgata")
taxontable <- new_entry("Cymbellafalsa", fix = "Cymbellafalsa", spe = NA, gen = "Cymbellafalsa")
taxontable <- new_entry("Cymbopleura angustata var. tenuis", fix = "Cymbopleura angustata-descripta++")
taxontable <- new_entry("Cymbopleura florentina var. brevis", fix = "Cymbopleura florentina")
taxontable <- new_entry("Cymbopleura naviculiformis var. laticapitata", fix = "Cymbopleura laticapitata")
taxontable <- new_entry("Cymbopleura pyrenaica", fix = "Cymbopleura pyrenaica")
taxontable <- new_entry("Cymbopleura rupicola var. rupicola", fix = "Cymbopleura")
taxontable <- new_entry("Delicata", fix = "Delicata", spe = NA, gen = "Delicata")
taxontable <- new_entry("Delicata verena var. verena", fix = "Delicata", spe = NA, gen = "Delicata")
taxontable <- new_genus("Denticula seminae", fix = "Neodenticula seminae", spe = "Neodenticula seminae", gen = "Neodenticula", fam = "Bacillariaceae", ord = "Bacillariales", cla = "Bacillariophyceae")
taxontable <- new_genus("Detonia superba", fix = "Detonia dobrinae", spe = "Detonia dobrinae", gen = "Detonia", fam = "Bacillariophyta familia incertae sedis", ord = "Bacillariophyta ordo incertae sedis", cla = "Bacillariophyta classis incertae sedis")
taxontable <- new_genus("Diademoides", fix = "Diademoides", spe = NA, gen = "Diademoides", fam = "Scoliotropidaceae", ord = "Naviculales", cla = "Bacillariophyceae")
taxontable <- new_entry("Diadesmis paracontenta ssp. paracontenta", fix = "Diadesmis contenta")
taxontable <- new_entry("Diatoma hyemale var. maximum", fix = "Diatoma", spe = NA, gen = "Diatoma")
taxontable <- new_entry("Diatoma hyemale var. mesodon", fix = "Diatoma", spe = NA, gen = "Diatoma")
taxontable <- new_entry("Dimeregramma", fix = "Dimeregramma", spe = NA, gen = "Dimeregramma")
taxontable <- new_genus("Diplomenora cocconeiformis", fix = "Diplomenora cocconeiformis", spe = "Diplomenora cocconeiformis", gen = "Diplomenora", fam = "Rhaphoneidaceae", ord = "Rhaphoneidales", cla = "Bacillariophyceae")
taxontable <- new_entry("Diploneis abscondita", fix = "Diploneis abscondita")
taxontable <- new_entry("Diploneis calcilacustris", fix = "Diploneis calcilacustris")
taxontable <- new_entry("Diploneis hinziae", fix = "Diploneis hinziae")

taxontable <- new_entry("Diploneis oblongella var. ovalis", fix = "Diploneis elliptica/oblongella/ovalis/marginestrata/minuta/modica")
taxontable <- new_entry("Diploneis oblongellopsis", fix = "Diploneis oblongellopsis")
taxontable <- new_entry("Diploneis papula var. papula", fix = "Diploneis papula")
taxontable <- new_entry("Diploneis praetermissa", fix = "Diploneis praetermissa")
taxontable <- new_entry("Diploneis tirolensis", fix = "Diploneis tirolensis")
taxontable <- new_entry("Discostella stelligera var. elliptica", fix = "Discostella", spe = NA, gen = "Discostella")
taxontable <- new_genus("Ehrenbergiulva granulosa", fix = "Ehrenbergiulva granulosa", spe = "Ehrenbergiulva granulosa", gen = "Ehrenbergiulva", fam = "Thalassiosiraceae", ord = "Thalassiosirales", cla = "Mediophyceae")
taxontable <- new_entry("Encyonema abnormal form", fix = "Encyonema", spe = NA, gen = "Encyonema")
taxontable <- new_entry("Encyonema bonapartei", fix = "Encyonema bonapartei")
taxontable <- new_entry("Encyonema lunatum var. borealis", fix = "Encyonema lunatum")
taxontable <- new_entry("Encyonema microrobusta", fix = "Encyonema microrobusta")
taxontable <- new_entry("Encyonema minutum abnormal form", fix = "Encyonema silesicacum/minutum/lange-bertalotii")
taxontable <- new_entry("Encyonema norvegicum var. capitatum", fix = "Encyonema norvegicum")
taxontable <- new_entry("Encyonema silesiacum abnormal form", fix = "Encyonema silesicacum/minutum/lange-bertalotii")
taxontable <- new_entry("Encyonopsis cesatii abnormal form", fix = "Encyonopsis cesatii")
taxontable <- new_entry("Encyonopsis neerlandica", fix = "Encyonopsis neerlandica")
taxontable <- new_entry("Eolimna chistiakovae", fix = "Sellaphora chistiakovae")
taxontable <- new_entry("Epithemia gibba", fix = "Rhopalodia gibba Complex")
taxontable <- new_entry("Epithemia sorex var. lapponica", fix = "Epithemia amphicephala")
taxontable <- new_entry("Eunotia arcubus var. bidens", fix = "Eunotia", spe = NA, gen = "Eunotia")
taxontable <- new_entry("Eunotia cisalpina", fix = "Eunotia cisalpina")
taxontable <- new_entry("Eunotia enigmatica", fix = "Eunotia enigmatica")
taxontable <- new_entry("Eunotia exigua abnormal form", fix = "Eunotia  exigua/elegans Complex")
taxontable <- new_entry("Eunotia exigua var. tenella", fix = "Eunotia  exigua/elegans Complex")
taxontable <- new_entry("Eunotia formicina", fix = "Eunotia formicina")

taxontable <- new_entry("Eunotia metamonodon", fix = "Eunotia metamonodon")
taxontable <- new_entry("Eunotia myrmica", fix = "Eunotia myrmica")
taxontable <- new_entry("Eunotia nanoslusitanica", fix = "Eunotia nanolusitanica")
taxontable <- new_entry("Eunotia orthohedra", fix = "Eunotia orthohedra")
taxontable <- new_entry("Eunotia pectinalis var. biconstricta", fix = "Eunotia pectinalis Complex")
taxontable <- new_entry("Eunotia semicircularis", fix = "Eunotia semicircularis")
taxontable <- new_entry("Eunotia subantarctica", fix = "Eunotia subantarctica")
taxontable <- new_entry("Eunotia subherkiniensi", fix = "Eunotia subherkiniensi")
taxontable <- new_entry("Eunotia sudetica var. incisa", fix = "Eunotia", spe = NA, gen = "Eunotia")
taxontable <- new_genus("Eunotogramma", fix = "Eunotogramma", spe = NA, gen = "Eunotogramma", fam = "Anaulaceae", ord = "Anaulales", cla = "Mediophyceae")
taxontable <- new_entry("Eunotogramma laevis", fix = "Eunotogramma laeve")
taxontable <- new_entry("Fragilaria aquaplus", fix = "Fragilaria aquaplus")
taxontable <- new_entry("Fragilaria arcus var. arcus", fix = "Synedra cyclopum/Hannaea arcus")
taxontable <- new_entry("Fragilaria binodis", fix = "Pseudostaurosira brevistriata complex")
taxontable <- new_entry("Fragilaria brevistriata var. elliptica", fix = "Pseudostaurosira brevistriata complex")
taxontable <- new_entry("Fragilaria brevistriata var. inflata", fix = "Pseudostaurosira brevistriata complex")
taxontable <- new_entry("Fragilaria delicatissima var. angustissima", fix = "Fragilaria tenera complex")
taxontable <- new_genus("Fragilaria geocollegarum", fix = "Pseudostaurosiropsis geocollegarum", spe = "Pseudostaurosiropsis geocollegarum", gen = "Pseudostaurosiropsis", fam = "Staurosiraceae", ord = "Fragilariales", cla = "Bacillariophyceae")
taxontable <- new_genus("Fragilaria gessneri", fix = "Desikaneis simplex", spe = "Desikaneis simplex", gen = "Desikaneis", fam = "Fragilariaceae", ord = "Fragilariales", cla = "Bacillariophyceae")
taxontable <- new_entry("Fragilaria grunowii", fix = "Ulnaria grunowii")
taxontable <- new_entry("Fragilaria longifusiformis subsp. eurofusiformis", fix = "Fragilaria longifusiformis")
taxontable <- new_entry("Fragilaria microvaucheriae", fix = "Fragilaria microvaucheriae")
taxontable <- new_entry("Fragilaria mutabilis", fix = "Staurosirella pinnata complex")
taxontable <- new_entry("Fragilaria pinnata var. lancettula", fix = "Punctastriata lancettula")

taxontable <- new_entry("Fragilaria producta var. acuta", fix = "Fragilaria virescens complex")
taxontable <- new_entry("Fragilaria sandellii", fix = "Fragilaria sandellii")
taxontable <- new_entry("Fragilaria saxoplanctonica", fix = "Fragilaria saxoplanctonica")
taxontable <- new_entry("Fragilaria spec. cf. subsalina", fix = "Fragilaria cassubica")
taxontable <- new_entry("Fragilaria tenera abnormal form", fix = "Fragilaria tenera complex")
taxontable <- new_entry("Fragilaria tenera var. lemanensis", fix = "Fragilaria tenera complex")
taxontable <- new_entry("Fragilaria tenuissima", fix = "Fragilaria tenuissima")
taxontable <- new_entry("Fragilaria ulna var. amphirhynchus", fix = "Ulnaria amphirhynchus")
taxontable <- new_entry("Fragilaria ulna var. oxyrhynchus", fix = "Ulnaria oxyrhynchus")
taxontable <- new_entry("Fragilaria ulna var. ungeriana", fix = "Ulnaria ungeriana")
taxontable <- new_entry("Fragilaria vaucheriae var. distans", fix = "Fragilaria capucina complex")
taxontable <- new_entry("Fragilariforma javanica", fix = "Fragilariforma javanica")
taxontable <- new_genus("Frankophila", fix = "Frankophila", spe = NA, gen = "Frankophila", fam = "Fragilariaceae", ord = "Fragilariales", cla = "Bacillariophyceae")
taxontable <- new_entry("Frustulia quadrisinuata ssp. meridiana", fix = "Frustulia quadrisinuata")
taxontable <- new_entry("Frustulia regula", fix = "Frustulia regula")
taxontable <- new_entry("Frustulia rhomboides var. baicalensis", fix = "Frustulia baicalensis")
taxontable <- new_entry("Frustulia rhomboides var. compacta", fix = "Frustulia rhomboides Complex")
taxontable <- new_entry("Frustulia rhomboides var. pusilla", fix = "Frustulia rhomboides Complex")
taxontable <- new_entry("Frustulia rhomboides var. rhodesica", fix = "Frustulia rhomboides Complex")
taxontable <- new_entry("Geissleria modica", fix = "Navigeia modica")
taxontable <- new_entry("Geissleria tagensis", fix = "Navigeia tagensis")
taxontable <- new_entry("Genkalia", fix = "Genkalia", spe = NA, gen = "Genkalia")
taxontable <- new_genus("Germainiella enigmatica", fix = "Germainiella enigmatica", spe = "Germainiella enigmatica", gen = "Germainiella", fam = "Naviculaceae", ord = "Naviculales", cla = "Bacillariophyceae")
taxontable <- new_entry("Gomphoneis inconspicua", fix = "Gomphoneis inconspicua")
taxontable <- new_entry("Gomphoneis oblongum", fix = "Gomphoneis oblonga")
taxontable <- new_entry("Gomphonema affine abnormal form", fix = "Gomphonema gracile complex")

taxontable <- taxontable[!duplicated(taxontable$original_name)]

check_taxon_table(taxontable)

taxontable[species == "Achnanthes minutissima", 
           c("fixed_name", "species", "genus", "family") := 
                   .("Achnanthidium minutissimum", "Achnanthidium minutissimum", "Achnanthidium", "Achnanthidiaceae")]

taxontable[genus == "Muelleria", family := "Neidiaceae"]

taxontable[family == "Achnanthidiaceae", unique(order)]
taxontable[family == "Cocconeidaceae", unique(order)]
taxontable[family == "Stephanodiscaceae", unique(genus)]
taxontable[family == "Achnanthidiaceae", order := "Achnanthales"]
taxontable[family == "Cocconeidaceae", order := "Cocconeidales"]
taxontable[family == "Stephanodiscaceae", order := "Stephanodiscales"]
taxontable[order == "Aulacoseirales", class := "Coscinodiscophyceae"]
taxontable[order == "Triceratiales" , class := "Mediophyceae"]



TU <- unique(data$taxon) |> sort()
TU <- setdiff(TU, taxontable$original_name)

saveRDS(taxontable, paste0("data/diatoms/",Sys.Date(),"_taxontable_diatoms.rds"))